### ISSUE TITLE
email/password errors

### ISSUE THREAD

**Issue by diggeridoo** [yihong0618/Runtastic#2]
Hi, I'm having this error messages in terminal, but the mail/password are correct:
```
Start to save gpx in GPX_OUT please wait
Traceback (most recent call last):
  File "/usr/local/bin/runtastic", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/runtastic.py", line 301, in main
    loop.run_until_complete(future)
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/runtastic.py", line 267, in run
    await _login(email, password)
  File "/usr/local/lib/python3.9/site-packages/runtastic.py", line 95, in _login
    raise Exception("Please make sure your email or password are correct")
Exception: Please make sure your email or password are correct
```

**Comment by yihong0618** [comment]
@diggeridoo
Test today its OK.

Can you make sure that your account can login in app or webside.
Because as I know, runtastic ban the accounts in China If that account not change to other  areas.
 
![image](https://user-images.githubusercontent.com/15976103/99470657-0a485f80-2980-11eb-96b5-ade5fad0c667.png)

**Comment by diggeridoo** [comment]
Hi thanks for check it, I've tested both app and web and login is ok, from Spain.

Tried several combinations but doesn't work, not sure where is the problem, I'm using this command line in terminal:
`runtastic -e my@email.com -p mypassword`
From the master file downloaded. Always output the same error above.
runtastic_sync is different file?

**Comment by yihong0618** [comment]
@diggeridoo
sorry for that confuse, `runtastic_sync ` is from my another repo cli https://github.com/yihong0618/running_page
I tested in wrong file.

and I test again for Runtatic, and it worked as well

I don't know its python version problem or something else.

Can you help me test
1. pip3 install -U runtastic (update to lastest runtastic) to see if its ok
2. try python3.6 or python3.7
3. quote your password runtastic -e my@email.com -p 'mypassword'

**Comment by diggeridoo** [comment]
Yeah! that worked, it seems to be the quotes, password has to have them in order to be recognised.
I run the install upgrade but it was skipped "Requirement already satisfied"
So it was just the quote issue.

Thanks for your help and for this great piece of software!

**Comment by yihong0618** [comment]
@diggeridoo you can also try running_page
Cool

**Comment by diggeridoo** [comment]
Great! I'll take a look to the other code
Thanks!
