### ISSUE TITLE
Filename Date

### ISSUE THREAD

**Issue by Cizzzzz** [yihong0618/Runtastic#3]
Hi, thank you so much for this export possibly. 
Could you have a look at the name of the GPX files. It seems they are now on Unix timestamp format. For example: 1625235980881.gpx
However in the screenshots they are in a readable Date/Time format.
How do I achieve that, like in the screenshot?
Thanks.

**Comment by yihong0618** [comment]
Yep, I changed the time format...
Because of its easy for [running_page](https://github.com/yihong0618/running_page) but because of  `DCMA` it has been deleted.

you can easily write a script for change all the name.

like 
```python
import os

file_list = os.listdir('file_dir')
for f in file_list:
    change_name(f)
```
