### ISSUE TITLE
Login does not work anymore

### ISSUE THREAD

**Issue by hofst** [yihong0618/Runtastic#4]
Hi,

First: Great python package, it has been serving me very well so far.
However, it seems like it does not work anymore. It currently fails with "permission denied" (while I can still login to my accounts in the website). Maybe the api endpoint or tokens have changed?

**Comment by yihong0618** [comment]
> Hi,
> 
> 
> 
> First: Great python package, it has been serving me very well so far.
> 
> However, it seems like it does not work anymore. It currently fails with "permission denied" (while I can still login to my accounts in the website). Maybe the api endpoint or tokens have changed?

seems that they revert the appkey or change the api，will take a look later
But I am not sure I can solve it or not.

**Comment by hofst** [comment]
Thank you! :-)

**Comment by yihong0618** [comment]
> Thank you! :-) 

Looked into it seems a little hard for me.

**Comment by yihong0618** [comment]
@hofst 
With @NotSyntax's  great job I think its rework now, and I published it to `pypi` 
you can `pip3 install -U runtastic` or just clone the repo to give a test~

**Comment by hofst** [comment]
works great, thank you! :-)

**Comment by yihong0618** [comment]
> works great, thank you! :-)

Thanks you like it~
