### ISSUE TITLE
The package works no more?

### ISSUE THREAD

**Issue by 11100010** [yihong0618/Runtastic#7]
I'm pretty sure my email and password correctly put in.

The error as below:

Anybody could help, please.
```
➜  run  runtastic -e "xxxxx@gmail.com" -p "yyyyy" 
Start to save gpx in GPX_OUT please wait
Traceback (most recent call last):
  File "/opt/homebrew/bin/runtastic", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/runtastic.py", line 301, in main
    loop.run_until_complete(future)
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/runtastic.py", line 267, in run
    await _login(email, password)
  File "/opt/homebrew/lib/python3.11/site-packages/runtastic.py", line 95, in _login
    raise Exception("Please make sure your email or password are correct")
Exception: Please make sure your email or password are correct
```

**Comment by 11100010** [comment]
𝖓𝖔𝖕𝖊

**Comment by yihong0618** [comment]
@11100010 runtastic change its way...
I will try to fix but need time

**Comment by yihong0618** [comment]
@11100010 fixed 
please try the new version

**Comment by 11100010** [comment]
> @11100010 fixed please try the new version

Looks like Adidas Running had changed the way it worked again.
The exact errors just happened right now. What a shame:(

**Comment by yihong0618** [comment]
@11100010 just try and it works well

also runtastic add time limit  you can not login too many times at a short time
![image](https://github.com/yihong0618/Runtastic/assets/15976103/1ed4df06-526b-4780-9cca-c51ae728f0d6)

**Comment by 11100010** [comment]
> @11100010 just try and it works well
> 
> also runtastic add time limit you can not login too many times at a short time ![image](https://user-images.githubusercontent.com/15976103/267962722-1ed4df06-526b-4780-9cca-c51ae728f0d6.png)

Just reinstalled, but I couldn't figure out what was wrong, please take a look at the error: 
![D77C5154-3275-42C4-AC99-E1A566BF24C0](https://github.com/yihong0618/Runtastic/assets/87060114/d0537c3c-99ca-41d9-92b9-08553d323212)

**Comment by 11100010** [comment]
> > @11100010 just try and it works well
> > also runtastic add time limit you can not login too many times at a short time ![image](https://user-images.githubusercontent.com/15976103/267962722-1ed4df06-526b-4780-9cca-c51ae728f0d6.png)
> 
> Just reinstalled, but I couldn't figure out what was wrong, please take a look at the error: ![D77C5154-3275-42C4-AC99-E1A566BF24C0](https://user-images.githubusercontent.com/87060114/268145680-d0537c3c-99ca-41d9-92b9-08553d323212.jpeg)

I must scold myself for the mistake so I'll remember it for later: "It's the version, stupid."
