### ISSUE TITLE
The output has no heart rate data?

### ISSUE THREAD

**Issue by 11100010** [yihong0618/Runtastic#8]
I can see a function named: "decode_heart_rate_trace(trace)" in the code.
But I don't see the heart rate data in the output files.
Pretty sure my running sessions on Adidas Running has the heart rate data.
Any solution for this issue? thank you.

**Comment by yihong0618** [comment]
it should have, when I download them.
if there is a bug or the api change from upstrem, you can try to debug it or make a pull request.

sorry I did not use Runtastic for a long time
